### PR TITLE
use liquid 2.5.1

### PR DESCRIPTION
**Pull request by espen**

### CODE REVIEW

**Comment by espen** [comment]
Prior versions to 2.5.1 has a critical information leak. Fix: https://github.com/Shopify/liquid/pull/230

**Comment by espen** [comment]
Hey @bigcartel any chance of updating the gemspec to the latest liquid version?

**Comment by outerim** [comment]
I don't think there's actually any reason this needs to depend on a specific version. Probably best to let it use the latest version of whatever people happen to have in their own Gemfile's. Your thoughts @espen?

**Comment by espen** [comment]
Well the API might change so I suggest that the gemspec specify version 2.x. I guess that should be '~> 2'.

**Comment by outerim** [comment]
If you want to update the PR to do that (squashing the commits) and also update the Gemfile similarly I think this would be good to merge.

**Comment by espen** [comment]
I assume that Travis error is due to bundler trying install Rails 4.0 on Ruby 1.8.7 which is not supported.

**Comment by espen** [comment]
Is there anything I can change in this PR to get it merged @biscuitvile ?

**Pull request closed without merging**
